name: CD - production

on:
  push:
    branches: [ main ]
env:
  NEXT_PUBLIC_BASE_PATH: ''
  NEXT_PUBLIC_DOCSEARCH_APP_ID: ${{ secrets.NEXT_PUBLIC_DOCSEARCH_APP_ID }}
  NEXT_PUBLIC_DOCSEARCH_API_KEY: ${{ secrets.NEXT_PUBLIC_DOCSEARCH_API_KEY }}
  NEXT_PUBLIC_DOCSEARCH_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_DOCSEARCH_INDEX_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run concat
      - run: mv allPageSourceFiles.md ./build/
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_PRODUCTION_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_PRODUCTION_SECRET }}
          aws-region: eu-west-1
      - run: aws s3 sync ./build ${{ secrets.AWS_S3_PRODUCTION_PATH }} --delete
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }} --paths '/*'
