name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  checkChangedFiles:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.added_modified }}
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          format: 'csv'
          filter: '*.mdx?'

  test:
    runs-on: ubuntu-latest
    needs: checkChangedFiles
    if: ${{ needs.checkChangedFiles.outputs.files != '' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test -- --reporter JSON --reporter-option output=mocha-results.json --filesToCheck=${{ needs.checkChangedFiles.outputs.files }}
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: mocha-results
          path: mocha-results.json
      - uses: dorny/test-reporter@v1
        with:
          artifact: mocha-results
          name: mocha-results
          path: 'artifacts\mocha-results.json'
          reporter: mocha-json
          only-summary: 'false'
