name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: npm run test -- --filesToCheck=${{ steps.files.outputs.added_modified }}
