name: Tests

on: [pull_request]

jobs:

  checkChangedFiles:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.added_modified }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          format: 'csv'
          filter: |
            *.md
            *.mdx
      - run: npm run test -- --filesToCheck=${{ steps.files.outputs.added_modified }}

  test:
    runs-on: ubuntu-latest
    needs: checkChangedFiles
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test -- --filesToCheck=${{ needs.checkChangedFiles.outputs.files }}
