name: Vale

on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: docs
          reporter: github-pr-check
          filter_mode: added
          vale_flags: "--glob=*.{md,mdx} --config='.vale.ini'"